-- MySQL Script generated by MySQL Workbench
-- Thu Jun  4 10:29:46 2026
-- Model: New Model    Version: 1.0
-- MySQL Workbench Forward Engineering

SET @OLD_UNIQUE_CHECKS=@@UNIQUE_CHECKS, UNIQUE_CHECKS=0;
SET @OLD_FOREIGN_KEY_CHECKS=@@FOREIGN_KEY_CHECKS, FOREIGN_KEY_CHECKS=0;
SET @OLD_SQL_MODE=@@SQL_MODE, SQL_MODE='ONLY_FULL_GROUP_BY,STRICT_TRANS_TABLES,NO_ZERO_IN_DATE,NO_ZERO_DATE,ERROR_FOR_DIVISION_BY_ZERO,NO_ENGINE_SUBSTITUTION';

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
DROP SCHEMA IF EXISTS `mydb` ;

-- -----------------------------------------------------
-- Schema mydb
-- -----------------------------------------------------
CREATE SCHEMA IF NOT EXISTS `mydb` DEFAULT CHARACTER SET utf8 ;
USE `mydb` ;

-- -----------------------------------------------------
-- Table `mydb`.`Гостиница`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Гостиница` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Гостиница` (
  `id1` INT NOT NULL AUTO_INCREMENT,
  `Гостинница` VARCHAR(100) NOT NULL,
  `Цена` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id1`),
  CONSTRAINT `гостиница`
    FOREIGN KEY ()
    REFERENCES `mydb`.`Гостиница` ()
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Номера`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Номера` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Номера` (
  `id_Номера` INT NOT NULL,
  `Номер комнаты` VARCHAR(45) NOT NULL,
  `Тип номера` VARCHAR(45) NOT NULL,
  `Цена за сутки` DECIMAL(10,2) NOT NULL,
  PRIMARY KEY (`id_Номера`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Гости`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Гости` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Гости` (
  `id_Гостя` INT NOT NULL,
  `имя` VARCHAR(45) NOT NULL,
  `фамилия` VARCHAR(45) NOT NULL,
  `телефон` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Гостя`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Услуги`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Услуги` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Услуги` (
  `id_Услуги` INT NOT NULL,
  `Название услуги` VARCHAR(45) NOT NULL,
  `Стоимость` DECIMAL(10,2) NOT NULL,
  `Доп.услуги_id_бронирования` VARCHAR(45) NOT NULL,
  PRIMARY KEY (`id_Услуги`))
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Бронирование`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Бронирование` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Бронирование` (
  `id_Бронирования` INT NOT NULL,
  `Дата заселения` DATE NOT NULL,
  `Дата выселения` DATE NOT NULL,
  `статус бронирования` VARCHAR(45) NOT NULL,
  `Гости_id_Гостя` INT NOT NULL,
  `Номера_id_Номера` INT NOT NULL,
  PRIMARY KEY (`id_Бронирования`),
  INDEX `fk_Бронирование_Гости1_idx` (`Гости_id_Гостя` ASC) VISIBLE,
  INDEX `fk_Бронирование_Номера1_idx` (`Номера_id_Номера` ASC) VISIBLE,
  CONSTRAINT `fk_Бронирование_Гости1`
    FOREIGN KEY (`Гости_id_Гостя`)
    REFERENCES `mydb`.`Гости` (`id_Гостя`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Бронирование_Номера1`
    FOREIGN KEY (`Номера_id_Номера`)
    REFERENCES `mydb`.`Номера` (`id_Номера`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


-- -----------------------------------------------------
-- Table `mydb`.`Доп.услуги`
-- -----------------------------------------------------
DROP TABLE IF EXISTS `mydb`.`Доп.услуги` ;

CREATE TABLE IF NOT EXISTS `mydb`.`Доп.услуги` (
  `id_Доп.услуги` INT NOT NULL,
  `количество` VARCHAR(45) NOT NULL,
  `дата предоставления` DATE NOT NULL,
  `Бронирование_id_Бронирования` INT NOT NULL,
  `Услуги_id_Услуги` INT NOT NULL,
  PRIMARY KEY (`id_Доп.услуги`),
  INDEX `fk_Доп.услуги_Бронирование1_idx` (`Бронирование_id_Бронирования` ASC) VISIBLE,
  INDEX `fk_Доп.услуги_Услуги1_idx` (`Услуги_id_Услуги` ASC) VISIBLE,
  CONSTRAINT `fk_Доп.услуги_Бронирование1`
    FOREIGN KEY (`Бронирование_id_Бронирования`)
    REFERENCES `mydb`.`Бронирование` (`id_Бронирования`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION,
  CONSTRAINT `fk_Доп.услуги_Услуги1`
    FOREIGN KEY (`Услуги_id_Услуги`)
    REFERENCES `mydb`.`Услуги` (`id_Услуги`)
    ON DELETE NO ACTION
    ON UPDATE NO ACTION)
ENGINE = InnoDB;


SET SQL_MODE=@OLD_SQL_MODE;
SET FOREIGN_KEY_CHECKS=@OLD_FOREIGN_KEY_CHECKS;
SET UNIQUE_CHECKS=@OLD_UNIQUE_CHECKS;
