# pytest.ini

[pytest]
pythonpath = .
testpaths = tests
norecursedirs = .git .idea __pycache__ *.egg-info venv src

addopts = 
    -v
    --tb=short
    --strict-markers
    --cov=src
    --cov-report=term
    --cov-report=html

markers =
    unit: Unit tests
    integration: Integration tests